language: php
php:
  - "5.4"
  - "5.3"
before_script:
  - composer self-update
  - pear config-set preferred_state beta
  - pear config-set preferred_state stable
  - pear install pear/PHP_CodeSniffer
  - pear channel-discover components.ez.no
  - pear install ezc/ConsoleTools
  - pear config-set auto_discover 1
  - pear install pear.phpunit.de/phpcpd
  - pear install pear.phpunit.de/PHP_CodeCoverage
  - pear install -f pear.phpunit.de/phpdcd
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install --alldeps phpmd/PHP_PMD
  - phpenv rehash
script:
  - phpunit -c application/tests/phpunit.xml
  - phpmd . text codesize,unusedcode,naming,design --ignore=application/libraries/,application/archive/
  - phpcpd .
  - phpdcd .
  - phpcs --standard=PSR2 --extensions=php --ignore=*/libraries/*,*/archive/* .