language: php
php:
  - "5.4"
  - "5.3"
before_script:
  - composer self-update
  - pear config-set preferred_state beta
  - printf "\n" | pecl install imagick
  - echo "extension=imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - pear config-set preferred_state stable
  - pear install pear/PHP_CodeSniffer
  - pear channel-discover components.ez.no
  - pear install ezc/ConsoleTools
  - pear config-set auto_discover 1
  - pear install pear.phpunit.de/phpcpd
  - pear install pear.phpunit.de/PHP_CodeCoverage
  - pear install -f pear.phpunit.de/phpdcd
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install --alldeps phpmd/PHP_PMD
  - phpenv rehash
  - chmod +x .travis.setup.sh
  - ./.travis.setup.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - chmod +x .travis.tests.sh

env:
 - OMEKA_BRANCH=master

script:
  - ./.travis.tests.sh
  - phpcpd . --exclude=omeka
  - phpdcd . --exclude=omeka
  - phpcs --standard=PSR2 --extensions=php .  --ignore=omeka
  - phpmd . text codesize,unusedcode,naming,design --ignore=omeka